Update fr_FR.yml
RypoFalem/ArmorStandEditor pull request #13
Opened 2017-04-07 18:59 UTC by Niasio

2017-04-13 19:50 UTC, AmauryCarrade commented on src/main/resources/lang/fr_FR.yml
> -# Translation by Amaury Carrade
Why is my name removed from the head comment?

2017-04-13 19:53 UTC, Niasio commented on src/main/resources/lang/fr_FR.yml
> -# Translation by Amaury Carrade
I forgot you lol

2018-07-25 20:17 UTC, RypoFalem commented
Honestly, I don't know how to properly resolve the crediting conflict. I don't have any experience with this sort of thing. What's important to me is that everyone feels like they are getting the credit they deserve. Would it please both of you if the top 2 lines simply read:
```
# Original translation by AmauryCarrade
# Updated by Niasio -> https://github.com/Niasio
```

2018-07-25 20:59 UTC, Niasio commented
Yes, it's a solution that seems very fair for me :D

2018-07-26 16:26 UTC, AmauryCarrade commented
That's fine for me too :)

Or

```yaml
# Translations by Amaury Carrade (https://github.com/AmauryCarrade) and Niasio (https://github.com/Niasio)
```

2018-07-26 16:40 UTC, AmauryCarrade requested changes
While I was there, I left a few comments regarding the new French translations (as it's my native tongue).

Also, you use « armure » a lot to talk about armor stands, but they are armor… _stands_, so you may want to change this word to « valet » or « porte-armure ». :)

2018-07-26 16:40 UTC, AmauryCarrade commented on src/main/resources/lang/fr_FR.yml
> +  msg: "Astuces:
There is a space missing here before `:` (required in French typography).

2018-07-26 16:40 UTC, AmauryCarrade commented on src/main/resources/lang/fr_FR.yml
> +  1. Appuyez sur le bouton \"Changer d'Item dans la Main\" (par défaut F) tout en tenant l'outil d'édition pour cibler un support d'armure spécifique, si d'autres étages d'armure sont dans le chemin.
You should use french quotation marks. As example (you can copy paste if the character is missing from your keyboard layout):

```diff
- 1. Appuyez sur le bouton \"Changer d'Item dans la Main\" (par défaut F) tout en tenant l'outil d'édition pour cibler un support d'armure spécifique, si d'autres étages d'armure sont dans le chemin.
+ 1. Appuyez sur le bouton « changer un objet de main » (par défaut F) tout en tenant l'outil d'édition pour cibler un support d'armure spécifique, si d'autres armure sont sur le chemin.
```
In the meantime, I updated the key name to the one Minecraft uses in its French translation and improved the whole sentence a little bit.

2018-07-26 16:40 UTC, AmauryCarrade commented on src/main/resources/lang/fr_FR.yml
> +      5. Cliquez avec le bouton droit de la souris pour modifier à l'envers!"
There is a space missing here before `!` (required in French typography).

2018-07-26 16:40 UTC, AmauryCarrade commented on src/main/resources/lang/fr_FR.yml
> +  msg: "1. Tenez l'outil d'édition (<x>) dans votre main principale
There is a missing dot at the end of the sentence (and the dot is in others).

2018-07-26 16:40 UTC, AmauryCarrade commented on src/main/resources/lang/fr_FR.yml
> +  2. Vous pouvez mettre des étiquettes aux stands d'armure. Vous pouvez utiliser le symbole & pour créer des noms colorés.
« stand d'armure » → « valets » ?

2018-07-26 16:40 UTC, AmauryCarrade commented on src/main/resources/lang/fr_FR.yml
> +  3. Vous pouvez utiliser crouch + scroll wheel tout en maintenant l'outil d'édition pour changer Axis sans ouvrir le menu"
```diff
- 3. Vous pouvez utiliser crouch + scroll wheel tout en maintenant l'outil d'édition pour changer Axis sans ouvrir le menu"
+ 3. Vous pouvez vous accroupir puis utiliser la molette de la souris tout en maintenant l'outil d'édition pour changer d'axe de modification sans ouvrir le menu."
```
(Better and frenchier translation, plus the missing dot at the end.)

2018-07-26 16:40 UTC, AmauryCarrade commented on src/main/resources/lang/fr_FR.yml
> +  msg: "Plus d'info: https://github.com/RypoFalem/ArmorStandEditor/wiki"
There is a space missing here before `:` (required in French typography).

2018-07-26 16:40 UTC, AmauryCarrade commented on src/main/resources/lang/fr_FR.yml
> +  msg: Aide!
There is a space missing here before `!` (required in French typography). Also, is this `!` needed? I mean, it's there in the original English translation, but it feels a little bit weird.

May I suggest something like this, to keep the exclamation but with better phrasing.

```diff
- Aide!
+ À l'aide !
```

2018-07-26 16:40 UTC, AmauryCarrade commented on src/main/resources/lang/fr_FR.yml
> +    msg: Cliquez pour avoir de une aide!
That's not a french sentence. I suggest:

```diff
- Cliquez pour avoir de une aide!
+ Cliquez ici pour obtenir de l'aide
```

2018-08-14 17:20 UTC, merged

2018-08-14 17:35 UTC, RypoFalem commented
Suggestions also implemented.

https://github.com/RypoFalem/ArmorStandEditor/commit/4be0f89b0b95ea88bda053217399a4c8a0bc58b2

2018-08-14 17:48 UTC, AmauryCarrade commented
Thanks!